# Generated by Django 4.1.7 on 2023-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating',
            new_name='author_rating',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='comment_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='_rating',
            new_name='post_rating',
        ),
        migrations.AlterField(
            model_name='post',
            name='type_news',
            field=models.CharField(choices=[('PA', 'Cтатья'), ('PN', 'Новость')], default='PA', max_length=2),
        ),
    ]
